---
dist: xenial

language: rust

rust:
  - stable
  - beta
  - nightly

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - cargo install --force cargo-audit

install: cargo build

script:
  - cargo audit
  - cargo test --verbose

notifications:
  email:
    on_success: never
    on_failure: never
